#!/bin/bash

source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate mechanistic-trimming 
set -eu

ANNOTATION_TYPE=$1
PARAM_GROUP=$2
NCPU=$3
GENE_WEIGHT_TYPE=$4
LEFT_MOTIF_COUNT=$5
RIGHT_MOTIF_COUNT=$6
VALIDATION_DATA_DIR=$7
VALIDATION_TYPE=$8
VALIDATION_TRIM_TYPE=$9
VALIDATION_PRODUCTIVITY=${10}

Rscript $PWD/mechanistic-trimming/scripts/analysis_scripts/evaluate_relative_importance.R $ANNOTATION_TYPE $PARAM_GROUP $NCPU $MODEL_GROUP $GENE_WEIGHT_TYPE $LEFT_MOTIF_COUNT $RIGHT_MOTIF_COUNT $VALIDATION_DATA_DIR $VALIDATION_TYPE $VALIDATION_TRIM_TYPE $VALIDATION_PRODUCTIVITY


