#!/bin/bash

source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate exomotif2 
set -eu

ANNOTATION_TYPE=$1
TRIM_TYPE=$2
MOTIF_TYPE=$3
NCPU=$4
GENE_WEIGHT_TYPE=$5
LEFT_MOTIF_COUNT=$6
RIGHT_MOTIF_COUNT=$7
UPPER_TRIM_BOUND=$8
MODEL_TYPE=$9

Rscript $PWD/scripts/evaluate_models.R $ANNOTATION_TYPE $TRIM_TYPE $MOTIF_TYPE $NCPU $GENE_WEIGHT_TYPE $LEFT_MOTIF_COUNT $RIGHT_MOTIF_COUNT $UPPER_TRIM_BOUND $MODEL_TYPE 
