#!/bin/bash
source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate mechanistic-trimming 
set -eu

ANNOTATION_TYPE=$1
DATA_GROUP=$2
TRIM_TYPE=$3
PRODUCTIVITY=$4
MOTIF_TYPE=$5
NCPU=$6
GENE_WEIGHT_TYPE=$7
LEFT_MOTIF_COUNT=$8
RIGHT_MOTIF_COUNT=$9
UPPER_TRIM_BOUND=${10}
LOWER_TRIM_BOUND=${11}
MODEL_TYPE=${12}
LEFT_SIDE_TERMINAL_MELT_LENGTH=${13:-NA}

Rscript $PWD/mechanistic-trimming/scripts/evaluate_coeffs.R $ANNOTATION_TYPE $DATA_GROUP $TRIM_TYPE $PRODUCTIVITY $MOTIF_TYPE $NCPU $GENE_WEIGHT_TYPE $LEFT_MOTIF_COUNT $RIGHT_MOTIF_COUNT $UPPER_TRIM_BOUND $LOWER_TRIM_BOUND $MODEL_TYPE $LEFT_SIDE_TERMINAL_MELT_LENGTH 

