#!/bin/bash

source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate exomotif2 
set -eu

ANNOTATION_TYPE=$1
TRIM_TYPE=$2
MOTIF_TYPE=$3
GENE_WEIGHT_TYPE=$4
UPPER_TRIM_BOUND=$5
PARTITION=$6
NCPU=$7
MODEL_TYPE=$8
PRODUCTIVITY=$9
LEFT_SIDE_TERMINAL_MELT_LENGTH=${10:-NA}

for LEFT_MOTIF_COUNT in {2..6..1}; do
    for RIGHT_MOTIF_COUNT in {2..6..1}; do
        COMMAND="sbatch -c $NCPU -p $PARTITION -q $PARTITION $HOME/exomotif/evaluate_single_model.sh $ANNOTATION_TYPE $TRIM_TYPE $PRODUCTIVITY $MOTIF_TYPE $NCPU $GENE_WEIGHT_TYPE $LEFT_MOTIF_COUNT $RIGHT_MOTIF_COUNT $UPPER_TRIM_BOUND $MODEL_TYPE $LEFT_SIDE_TERMINAL_MELT_LENGTH"
        $COMMAND
        echo "Running \`$COMMAND\`"
    done
done
