#!/bin/bash
source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate mechanistic-trimming 
set -eu

ANNOTATION_TYPE=$1
TRIM_TYPE=$2
PRODUCTIVITY=$3
MOTIF_TYPE=$4
NCPU=$5
MODEL_GROUP=$6
GENE_WEIGHT_TYPE=$7
LEFT_MOTIF_COUNT=$8
RIGHT_MOTIF_COUNT=$9
UPPER_TRIM_BOUND=${10}
MODEL_TYPE=${11}
LEFT_SIDE_TERMINAL_MELT_LENGTH=${12:-NA}

Rscript $PWD/scripts/fit_model.R $ANNOTATION_TYPE $TRIM_TYPE $PRODUCTIVITY $MOTIF_TYPE $NCPU $MODEL_GROUP $GENE_WEIGHT_TYPE $LEFT_MOTIF_COUNT $RIGHT_MOTIF_COUNT $UPPER_TRIM_BOUND $MODEL_TYPE $LEFT_SIDE_TERMINAL_MELT_LENGTH 

