#!/bin/bash

source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate mechanistic-trimming 
set -eu

ANNOTATION_TYPE=$1
TRIM_TYPE=$2
PRODUCTIVITY=$3
MOTIF_TYPE=$4
NCPU=$5
MODEL_GROUP=$6
GENE_WEIGHT_TYPE=$7
LEFT_MOTIF_COUNT=$8
RIGHT_MOTIF_COUNT=$9
UPPER_TRIM_BOUND=${10}
MODEL_TYPE=${11}
LEFT_SIDE_TERMINAL_MELT_LENGTH=${12}
VALIDATION_DATA_DIR=${13}
VALIDATION_TYPE=${14}
VALIDATION_TRIM_TYPE=${15}
VALIDATION_PRODUCTIVITY=${16}
LOSS_WEIGHT_TYPE=${17}

Rscript $PWD/scripts/validate_model.R $ANNOTATION_TYPE $TRIM_TYPE $PRODUCTIVITY $MOTIF_TYPE $NCPU $MODEL_GROUP $GENE_WEIGHT_TYPE $LEFT_MOTIF_COUNT $RIGHT_MOTIF_COUNT $UPPER_TRIM_BOUND $MODEL_TYPE $LEFT_SIDE_TERMINAL_MELT_LENGTH $VALIDATION_DATA_DIR $VALIDATION_TYPE $VALIDATION_TRIM_TYPE $VALIDATION_PRODUCTIVITY $LOSS_WEIGHT_TYPE


