#!/bin/bash

source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate mechanistic-trimming 
set -eu

ANNOTATION_TYPE=$1
DATA_GROUP=$2
PARAM_GROUP=$3
NCPU=$4
MODEL_GROUP=$5
GENE_WEIGHT_TYPE=$6
LEFT_MOTIF_COUNT=$7
RIGHT_MOTIF_COUNT=$8
MODEL_TYPE=$9
VALIDATION_DATA_DIR=${10}
VALIDATION_TYPE=${11}
VALIDATION_TRIM_TYPE=${12}
VALIDATION_PRODUCTIVITY=${13}
LOSS_WEIGHT_TYPE=${14}

Rscript $PWD/mechanistic-trimming/scripts/validate_model.R $ANNOTATION_TYPE $DATA_GROUP $PARAM_GROUP $NCPU $MODEL_GROUP $GENE_WEIGHT_TYPE $LEFT_MOTIF_COUNT $RIGHT_MOTIF_COUNT $MODEL_TYPE $VALIDATION_DATA_DIR $VALIDATION_TYPE $VALIDATION_TRIM_TYPE $VALIDATION_PRODUCTIVITY $LOSS_WEIGHT_TYPE


